// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvqnbnzbnzgpuckconte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cW5ibnpibnpncHVja2NvbnRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NjUzOTEsImV4cCI6MjA4NjA0MTM5MX0.tfUPwSQoTxXLMsB_UEp23CTI17XGx_60iL3_2i-mlF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
